[message]
broadcast_url = "https://api.line.me/v2/bot/message/broadcast"
reply_url = "https://api.line.me/v2/bot/message/reply"
push_url = "https://api.line.me/v2/bot/message/push"

[chatgpt]
chat_completions_url = "https://api.openai.com/v1/chat/completions"
model = "gpt-4o"
translate_model = "gpt-3.5-turbo"

[kagi]
kagi_summarize_url = "https://kagi.com/api/v0/summarize"
engine = "agnes"
target_language = "EN"

[rss]
feed_url = "https://www.daemonology.net/hn-daily/index.rss"
